name: deploy-on-object-storage
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: hugo

      - name: Deploy
        uses: ./.github/actions/deploy-on-scaleway
        with:
          source: './public/'
          target: 'site'
          az: 'fr-par'
          bucket: ${{ secrets.S3_BUCKET }}
          access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}